name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build ./Ela_Auth_Service.API/ELA_Auth_Service.csproj --configuration Release
    - name: UnitTests with real DB
      run: dotnet test ./ELA_Auth_Service.UnitTests/ELA_Auth_Service.UnitTests.csproj --configuration Release
    - name: IntegrationTests with real DB
      run: dotnet test ./ELA_Auth_Service.IntegrationTests/ELA_Auth_Service.IntegrationTests.csproj --configuration Release
